<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [4]:
import numpy as np

array_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [5]:
array_2D = array_1D.reshape(2,5)

print(array_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
array_num = np.array([0,2,0,3,4,0])

indices_noceros = []
indice = 0

for num in array_num:
    if num != 0:
        indices_noceros.append(indice)
    indice += 1 #Importante sumar fuera del for porque sino no muestra bien los indices!

print(f"Indeces distintos de 0: {indices_noceros}")

Indeces distintos de 0: [1, 3, 4]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [15]:
array_random = np.random.rand(3, 3)

print(array_random)

[[0.66112324 0.30648031 0.25316919]
 [0.31459423 0.77588626 0.37265266]
 [0.62369948 0.37154903 0.19987247]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [23]:
array_random_10 = np.random.randint(0, 11, (3,3))

maximo = np.max(array_random_10)


print(array_random_10)
print(f"Valor máximo: {maximo}")


[[3 7 3]
 [5 2 8]
 [9 6 4]]
Valor máximo: 9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [30]:
array_orden = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_orden_inv = -np.sort(-array_orden)

print(array_orden_inv)




[9 8 7 6 5 4 3 2 1 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [67]:
array_n = np.random.randint(1,25, (2,3,4), int)

print(array_n)

result_15 = np.where(array_n == 15)
if result_15[0].size > 0:
    print(f"\nSe encontro el valor 15 en los siguientes indices: {result_15}")
    print(f"El primer 15 se encuentra en la lista: {result_15[0][0]+1}, fila: {result_15[1][0]+1} y columna {result_15[2][0]+1}")
else:
    print("\nNo hay ningún valor 15")

print(f"\nTodos los elementos del primer array:\n{array_n[0]}")
print(f"\nLa última fila del último array:\n {array_n[-1, -1]}")

[[[10 20  8 15]
  [11  9 12 13]
  [ 2  9 20 11]]

 [[16  9 12  6]
  [20 20  1 20]
  [ 8 18 22  1]]]

Se encontro el valor 15 en los siguientes indices: (array([0]), array([0]), array([3]))
El primer 15 se encuentra en la lista: 1, fila: 1 y columna 4

Todos los elementos del primer array:
[[10 20  8 15]
 [11  9 12 13]
 [ 2  9 20 11]]

La última fila del último array:
 [ 8 18 22  1]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
array_tri = np.random.randint(1,31, (3,2,5), int)

print(array_tri)

print(f"\nSubarray que contiene los dos primeros elementos de cada fila del primer array:\n {array_tri[0 , : , : 2 ]}") 
#Primer array ([ 0 )
# De las filas --> todas ( , : )
# De las columnas --> los dos primeros ( , : 2]) 

print(f"\nSubarray de todas las filas de los dos últimos arrays:\n {array_tri[-2 : , : , :]}")
# Empezando por el final, desde el último hasta el penúltimo (últimos dos) --> ([ -2 : ,)
# De las filas --> todas ( : ,) 
# De las columnas --> todas ( : ])

[[[19  4 16 23 18]
  [ 3 30 24  8 22]]

 [[30 30 13 18 27]
  [18 10 25 17  4]]

 [[16  8 27  2  3]
  [27  1 16 11 29]]]

Subarray que contiene los dos primeros elementos de cada fila del primer array:
 [[19  4]
 [ 3 30]]

Subarray de todas las filas de los dos últimos arrays:
 [[[30 30 13 18 27]
  [18 10 25 17  4]]

 [[16  8 27  2  3]
  [27  1 16 11 29]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [79]:
array_tri_2 = np.random.randint(1,25, (4,3,2), int)
print("Array generado:")
print(array_tri_2)

array_tri_2[ 1 , : , : ] = 0
print("\nArray con ceros:")
print(array_tri_2)

array_tri_2[-1] = -1
print("\nArray con -1:")
print(array_tri_2)

Array generado:
[[[13 19]
  [ 8 15]
  [23 10]]

 [[14  4]
  [15  5]
  [20  8]]

 [[ 8 23]
  [18 17]
  [12  9]]

 [[24  9]
  [ 3  2]
  [ 2  6]]]

Array con ceros:
[[[13 19]
  [ 8 15]
  [23 10]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 8 23]
  [18 17]
  [12  9]]

 [[24  9]
  [ 3  2]
  [ 2  6]]]

Array con -1:
[[[13 19]
  [ 8 15]
  [23 10]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 8 23]
  [18 17]
  [12  9]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [145]:
array_tri_negativo = np.random.randint(-10,14, (2,4,3), int)
print("Array generado:")
print(array_tri_negativo)

mascara = array_tri_negativo > 5
elementos_filtrados = array_tri_negativo[mascara]

if elementos_filtrados.size > 0:
    print("\nArray con filtrado num > 5:")
    print(elementos_filtrados)
else:
    print("No hay elementos > 5")


mascara_2 = array_tri_negativo < 0
array_tri_negativo[mascara_2] = 0
print(f"\nNegativos a 0:\n {array_tri_negativo}")


Array generado:
[[[ 7 13  7]
  [13  9  2]
  [ 0  6  2]
  [ 8 10 11]]

 [[-3  2  6]
  [ 7 13 -7]
  [13  3 -1]
  [13 10  4]]]

Array con filtrado num > 5:
[ 7 13  7 13  9  6  8 10 11  6  7 13 13 13 10]

Negativos a 0:
 [[[ 7 13  7]
  [13  9  2]
  [ 0  6  2]
  [ 8 10 11]]

 [[ 0  2  6]
  [ 7 13  0]
  [13  3  0]
  [13 10  4]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
array_tri_3 = np.random.randint(1,28, (3,3,3,), int)
print(array_tri_3)

print(f"\nSubarray del segundo array de las dos primeras columnas:\n {array_tri_3[1, : , :2]}")

mascara_20 = array_tri_3[2 , : , :] > 20

print(f"\nTodos los elementos del tercer array que son mayores que 20:\n {array_tri_3[2][mascara_20]}")

[[[ 9 20 19]
  [19  4 18]
  [19 21  7]]

 [[19 13 25]
  [21  3 14]
  [ 5 25  2]]

 [[21  1 11]
  [12 12  1]
  [19 14 13]]]

Subarray del segundo array de las dos primeras columnas:
 [[19 13]
 [21  3]
 [ 5 25]]

Todos los elementos del tercer array que sean mayores que 20:
 [21]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:
array_random_diez = np.random.randint(0, 10, (2,5))

print(array_random_10)

maximo = np.max(array_random_diez)
print(f"El MAXIMO es: {maximo}")

minimo = np.min(array_random_diez)
print(f"El MINIMO es: {minimo}")


contador_array = 0
contador_fila = 0
contador_columna = 0

# Nose como solucionarlo :(

for array in array_random_diez:
    fila = 0
    for fila in array:
        columna = 0
        for valor in array:
            if valor == maximo:
                array_random_diez[contador_array][contador_fila][contador_columna] = 0
            if valor == minimo:
                array_random_diez[contador_array][contador_fila][contador_columna] = 0
            columna += 1
        fila +=1
    array += 1

print(array_random_diez)

[[4 7 9 2 4]
 [0 0 9 9 2]]
El MAXIMO es: 7
El MINIMO es: 0


TypeError: 'numpy.int32' object does not support item assignment

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.